function du2hat_dxi = du2hat_dxi(in1)
%DU2HAT_DXI
%    DU2HAT_DXI = DU2HAT_DXI(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jan-2017 22:22:47

X_1 = in1(1,:);
Y_1 = in1(2,:);
Z_1 = in1(3,:);
fx = in1(16,:);
r11 = in1(4,:);
r12 = in1(7,:);
r13 = in1(10,:);
r21 = in1(5,:);
r22 = in1(8,:);
r23 = in1(11,:);
r31 = in1(6,:);
r32 = in1(9,:);
r33 = in1(12,:);
tx = in1(13,:);
ty = in1(14,:);
tz = in1(15,:);
t2 = X_1.*r31;
t3 = Y_1.*r32;
t4 = Z_1.*r33;
t5 = t2+t3+t4+tz;
t6 = X_1.*r11;
t7 = Y_1.*r12;
t8 = Z_1.*r13;
t9 = t6+t7+t8+tx;
t10 = 1.0./t5.^2;
t11 = 1.0./t5;
du2hat_dxi = [fx.*t11,0.0,-fx.*t9.*t10,-fx.*t9.*t10.*ty-X_1.*fx.*r21.*t9.*t10-Y_1.*fx.*r22.*t9.*t10-Z_1.*fx.*r23.*t9.*t10,fx.*t11.*tz+X_1.*fx.*r31.*t11+Y_1.*fx.*r32.*t11+Z_1.*fx.*r33.*t11+fx.*t9.*t10.*tx+X_1.*fx.*r11.*t9.*t10+Y_1.*fx.*r12.*t9.*t10+Z_1.*fx.*r13.*t9.*t10,-fx.*t11.*ty-X_1.*fx.*r21.*t11-Y_1.*fx.*r22.*t11-Z_1.*fx.*r23.*t11];
