function dv2hat_dxi = dv2hat_dxi(in1)
%DV2HAT_DXI
%    DV2HAT_DXI = DV2HAT_DXI(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jan-2017 22:22:48

X_1 = in1(1,:);
Y_1 = in1(2,:);
Z_1 = in1(3,:);
fy = in1(17,:);
r11 = in1(4,:);
r12 = in1(7,:);
r13 = in1(10,:);
r21 = in1(5,:);
r22 = in1(8,:);
r23 = in1(11,:);
r31 = in1(6,:);
r32 = in1(9,:);
r33 = in1(12,:);
tx = in1(13,:);
ty = in1(14,:);
tz = in1(15,:);
t2 = X_1.*r31;
t3 = Y_1.*r32;
t4 = Z_1.*r33;
t5 = t2+t3+t4+tz;
t6 = 1.0./t5;
t7 = X_1.*r21;
t8 = Y_1.*r22;
t9 = Z_1.*r23;
t10 = t7+t8+t9+ty;
t11 = 1.0./t5.^2;
dv2hat_dxi = [0.0,fy.*t6,-fy.*t10.*t11,-fy.*t6.*tz-X_1.*fy.*r31.*t6-Y_1.*fy.*r32.*t6-Z_1.*fy.*r33.*t6-fy.*t10.*t11.*ty-X_1.*fy.*r21.*t10.*t11-Y_1.*fy.*r22.*t10.*t11-Z_1.*fy.*r23.*t10.*t11,fy.*t10.*t11.*tx+X_1.*fy.*r11.*t10.*t11+Y_1.*fy.*r12.*t10.*t11+Z_1.*fy.*r13.*t10.*t11,fy.*t6.*tx+X_1.*fy.*r11.*t6+Y_1.*fy.*r12.*t6+Z_1.*fy.*r13.*t6];
